# Generated by Django 4.0.3 on 2022-03-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HackerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hacker_ip', models.CharField(max_length=100)),
                ('router_ip', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('web_bage', models.CharField(max_length=100)),
                ('attach_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
